// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3qSdTl8N-D4bKKjjmvHRbXagLZwnVzio',
    appId: '1:515794616987:web:4ceb7530f2f9b4a6ac7c3e',
    messagingSenderId: '515794616987',
    projectId: 'fir-auth-demo-26ebc',
    authDomain: 'fir-auth-demo-26ebc.firebaseapp.com',
    storageBucket: 'fir-auth-demo-26ebc.firebasestorage.app',
    measurementId: 'G-MDMLVR30X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJybqp4m-6ahZNpiurUZXICbpb3_yfbPA',
    appId: '1:515794616987:android:266816029dd4a711ac7c3e',
    messagingSenderId: '515794616987',
    projectId: 'fir-auth-demo-26ebc',
    storageBucket: 'fir-auth-demo-26ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGHy4eJr_iN8K6YMlsqdcppgX-_6E3tM',
    appId: '1:515794616987:ios:3f27464be2073279ac7c3e',
    messagingSenderId: '515794616987',
    projectId: 'fir-auth-demo-26ebc',
    storageBucket: 'fir-auth-demo-26ebc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALGHy4eJr_iN8K6YMlsqdcppgX-_6E3tM',
    appId: '1:515794616987:ios:3f27464be2073279ac7c3e',
    messagingSenderId: '515794616987',
    projectId: 'fir-auth-demo-26ebc',
    storageBucket: 'fir-auth-demo-26ebc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3qSdTl8N-D4bKKjjmvHRbXagLZwnVzio',
    appId: '1:515794616987:web:9b2a102a2a4874c9ac7c3e',
    messagingSenderId: '515794616987',
    projectId: 'fir-auth-demo-26ebc',
    authDomain: 'fir-auth-demo-26ebc.firebaseapp.com',
    storageBucket: 'fir-auth-demo-26ebc.firebasestorage.app',
    measurementId: 'G-MHY42EZ8EJ',
  );
}
